# .slather.yml
coverage_service: coveralls
workspace: SmartDesk3/SmartDesk3.xcworkspace
xcodeproj: SmartDesk3/SmartDesk3.xcodeproj
scheme: SmartDesk3
ignore:
  - SmartDesk3/Pods/*
  - SmartDesk3/Tests/*
