# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
cache: cocoapods
podfile: MVPTest/Podfile
before_install:
- rvm use $RVM_RUBY_VERSION
#- gem install cocoapods # Since Travis is not always on latest version
#- gem install slather
- gem install cocoapods xcpretty slather --no-ri --no-rdoc
- pod install --project-directory=MVPTest
install:
- bundle install --without=documentation --path ../travis_bundle_dir
script:
- xcodebuild test -workspace MVPTest/MVPTest.xcworkspace -scheme MVPTest -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.3.1' -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES | xcpretty
after_success:
- slather
- slather coverage -s --html --scheme MVPTest --workspace MVPTest/MVPTest.xcworkspace MVPTest/MVPTest.xcodeproj
