# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
#cache: cocoapods
#podfile: SmartDesk3/Podfile
before_install:
- rvm use $RVM_RUBY_VERSION
#- gem install cocoapods # Since Travis is not always on latest version
#- cd SmartDesk3 && pod install
install:
- bundle install --without=documentation --path ../travis_bundle_dir
script:
- xcodebuild test -workspace MVPTest/MVPTest.xcworkspace -scheme MVPTest -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.3.1' -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint --allow-warnings
after_success:
#- cd $TRAVIS_BUILD_DIR && slather
- slather coverage -s --scheme MVPTest --workspace MVPTest/MVPTest.xcworkspace MVPTest/MVPTest.xcodeproj
