# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

def pods
    pod 'SlideMenuControllerSwift'
    pod 'MBProgressHUD'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'SwiftyJSON'
end

target 'MVPTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pods

end

target 'MVPTestTests' do
    inherit! :search_paths
    # Pods for testing
    pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
