# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!

def base_pods
    
    pod 'REFrostedViewController', '~> 2.4.7' #left menu
    pod 'Fabric'
    pod 'Crashlytics'
    
end

def product_pods
    #Pods for each project
end

target 'SmartDesk3' do

    base_pods
    product_pods

end

target 'SmartDesk3Tests' do
    # Pods for testing
    base_pods
    product_pods
end

target 'SmartDesk3UITests' do
    # Pods for testing
    base_pods
    product_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
